version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: talentlabs_postgres
    environment:
      POSTGRES_DB: talentlabs
      POSTGRES_USER: talentlabs_user
      POSTGRES_PASSWORD: talentlabs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U talentlabs_user -d talentlabs"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
