name: Django CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                    POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        env:
            DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}
            SECRET_KEY: dummy-secret-for-ci

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r backend/requirements.txt
                  pip install pytest ruff

            - name: Run ruff lint and format check
              working-directory: backend
              run: ruff check .

            - name: Wait for Postgres
              run: |
                  until pg_isready -h localhost -p 5432; do
                    echo "Waiting for postgres..."
                    sleep 2
                  done

            - name: Run migrations
              working-directory: backend
              run: python manage.py migrate

            - name: Run tests
              working-directory: backend
              run: pytest
